apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: addresspool
      protocol: layer2
      addresses:
      - 192.168.1.25-192.168.1.50
