apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespaces.yaml
- helm-longhorn.yaml
- sealedsecrets-controller.yaml
- ./ddclient/ddclient-cronjob.yaml
- ./ddclient/ddclient-sealedsecret.yaml
- ./metallb/metallb-configmap.yaml
- ./metallb/metallb.yaml
