apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp
  namespace: pihole
  annotations:
    metallb.universe.tf/address-pool: production
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.25
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-udp
  namespace: pihole
  annotations:
    metallb.universe.tf/address-pool: production
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.25
