apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp
  namespace: pihole
  annotations:
    metallb.universe.tf/address-pool: staging
spec:
  type: LoadBalancer
  loadBalancerIP: 192.186.1.51
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-udp
  namespace: pihole
  annotations:
    metallb.universe.tf/address-pool: staging
spec:
  type: LoadBalancer
  loadBalancerIP: 192.186.1.51
