apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc
  namespace: pihole
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # selector:
  #   matchLabels:
  #     directory: etc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq
  namespace: pihole
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
#   selector:
#     matchLabels:
#       directory: dnsmasq.d
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pihole-etc
#   namespace: pihole
#   labels:
#     directory: etc
# spec:
#   accessModes:
#     - 
#   storageClassName: longhorn
#   resources:
#     requests:
#       storage: 2Gi
