apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespaces.yaml
- wireguard.yaml
- ./podinfo/podinfo-kustomize.yaml
- ./podinfo/podinfo-source.yaml
- ./pihole/pihole-deploy.yaml
- ./pihole/pihole-pvc.yaml
- ./pihole/pihole-svc.yaml
