kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: wireguard
  name: pvc-wireguard
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wireguard-configmap
  namespace: wiredguard
data:
  PUID: "1000"
  PGID: "1000"
  TZ: "Asia/Jeruslem"
  SERVERPORT: "51820"
  SERVERURL: "home.zipori.net"
  PEERS: "3"
  PEERDNS: "192.168.1.1"
  ALLOWEDIPS: "0.0.0.0/0, ::/0"
  INTERNAL_SUBNET: "192.168.1.0"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wireguard
  namespace: wiredguard
  labels:
    app: wireguard
spec:
  serviceName: "wireguard"
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
      - name: wireguard
        image: ghcr.io/linuxserver/wireguard:v1.0.20210223-ls17
        envFrom:
        - configMapRef:
            name: wireguard-configmap 
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - SYS_MODULE
          privileged: true
        volumeMounts:
          - name: wg-config
            mountPath: /config
          - name: host-volumes
            mountPath: /lib/modules
        ports:
        - containerPort: 51820
          protocol: UDP
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
        - name: wg-config
          persistentVolumeClaim:
            claimName: pvc-wireguard 
        - name: host-volumes
          hostPath:
            path: /lib/modules
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: wiredguard
  annotations:
    metallb.universe.tf/address-pool: production
spec:
  selector:
    app: wireguard
  ports:
    - name: 51820-tcp
      port: 51820
      targetPort: 51820
      protocol: UDP
  externalTrafficPolicy: Local
  type: LoadBalancer
  loadBalancerIP: 192.186.1.30
