apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: metallb-system
data:
  config: |
    address-pools:
    - name: staging
      protocol: layer2
      addresses:
      - 192.168.1.51-192.168.1.71
